// Path: codebuddy-provider/src/codebuddy/usage.ts
/**
 * CodeBuddy token-usage parsing (Token Usage).
 *
 * CodeBuddy's chat/completions response carries a `usage` object that mixes
 * OpenAI and Anthropic field names:
 *   - input:   `prompt_tokens` (OpenAI) or `input_tokens` (Anthropic)
 *   - output:  `completion_tokens` (OpenAI) or `output_tokens` (Anthropic)
 *   - cached:  `input_tokens_details.cached_tokens`
 *   - reasoning: `output_tokens_details.reasoning_tokens`
 *
 * This module normalizes the raw payload into a single `TokenUsage` shape used
 * by the Session Ledger and provider logging. It is pure logic with zero
 * `vscode` dependency so it can be unit-tested in isolation.
 *
 * Parsing is defensive: missing, malformed, non-finite, or negative values
 * degrade to zero rather than throwing, so a partial usage chunk never breaks
 * a chat stream.
 */

export interface TokenUsage {
  /** Tokens sent to the model (prompt). */
  input: number;
  /** Tokens generated by the model (completion). */
  output: number;
  /** Prompt tokens served from cache. */
  cached: number;
  /** Output tokens used for extended reasoning/thinking. */
  reasoning: number;
}

/** Zero-valued TokenUsage — the safe fallback for any malformed input. */
export const EMPTY_USAGE: TokenUsage = { input: 0, output: 0, cached: 0, reasoning: 0 };

/**
 * Normalize a CodeBuddy usage payload into `TokenUsage`. Accepts the raw
 * response usage object (or `undefined`/`null` for absence). Never throws.
 */
export function parseCodeBuddyUsage(raw: unknown): TokenUsage {
  if (typeof raw !== 'object' || raw === null) {
    return { ...EMPTY_USAGE };
  }
  const u = raw as Record<string, unknown>;

  const details = (value: unknown): Record<string, unknown> | undefined => {
    if (typeof value !== 'object' || value === null) {
      return undefined;
    }
    return value as Record<string, unknown>;
  };

  return {
    input: toNonNegativeNumber(u.prompt_tokens, u.input_tokens),
    output: toNonNegativeNumber(u.completion_tokens, u.output_tokens),
    cached: toNonNegativeNumber(details(u.input_tokens_details)?.cached_tokens, undefined),
    reasoning: toNonNegativeNumber(details(u.output_tokens_details)?.reasoning_tokens, undefined),
  };
}

/** First valid non-negative finite number among the candidates, else 0. */
function toNonNegativeNumber(...candidates: unknown[]): number {
  for (const c of candidates) {
    if (typeof c === 'number' && Number.isFinite(c) && c >= 0) {
      return c;
    }
  }
  return 0;
}

/**
 * The OpenAI-compatible usage shape Copilot consumes from a
 * `LanguageModelDataPart` whose mimeType is the `usage` custom part (see
 * `CustomDataPartMimeTypes.Usage` in the Copilot extension). Copilot's
 * `isApiUsage` guard requires `prompt_tokens`/`completion_tokens`/`total_tokens`
 * to be numbers; `total_tokens` drives the Session Info / Context Window widget
 * (`usedTokens = prompt + completion`, denominator = model maxInput+maxOutput).
 */
export interface ApiUsage {
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
  prompt_tokens_details?: { cached_tokens: number };
  completion_tokens_details?: { reasoning_tokens: number };
}

/**
 * Convert a normalized `TokenUsage` into the OpenAI-compatible `ApiUsage`
 * shape so the provider can report real token consumption back to Copilot.
 */
export function toApiUsage(usage: TokenUsage): ApiUsage {
  return {
    prompt_tokens: usage.input,
    completion_tokens: usage.output,
    total_tokens: usage.input + usage.output,
    prompt_tokens_details: { cached_tokens: usage.cached },
    completion_tokens_details: { reasoning_tokens: usage.reasoning },
  };
}

/**
 * Format a `TokenUsage` into a single-line, human-readable string for the
 * provider's output channel.
 *
 * Example:
 *   `input 1280 · output 96 · cached 1100 · reasoning 40`
 */
export function formatTokenUsage(usage: TokenUsage): string {
  return (
    `input ${usage.input} · output ${usage.output}` +
    ` · cached ${usage.cached} · reasoning ${usage.reasoning}`
  );
}

/**
 * Aggregate one request's usage into a single `TokenUsage`.
 *
 * A single request may carry usage on more than one stream chunk (e.g. a
 * partial chunk plus a final usage chunk). This normalizes each payload and
 * keeps the first non-empty result, so repeated chunks count once and the
 * ledger is not double-counted. Returns all-zero when no chunk carried usage.
 */
export function aggregateRequestUsage(chunks: readonly unknown[]): TokenUsage {
  for (const chunk of chunks) {
    const usage = parseCodeBuddyUsage(chunk);
    if (usage.input > 0 || usage.output > 0) {
      return usage;
    }
  }
  return { ...EMPTY_USAGE };
}
